/**
 * Manager per il container gluetun (ProtonVPN tunnel).
 *
 * Flusso semplificato (login Proton, niente chiavi WireGuard):
 *   1. L'utente inserisce le credenziali OpenVPN/IKEv2 di Proton (username
 *      e password dedicati, NON la password dell'account) nella UI /configure.
 *   2. /api/vpn/setup chiama writeProtonLoginEnv() che scrive un env_file
 *      cifrato a parte e un file di env "plain" sul volume condiviso, in
 *      formato compatibile con `env_file:` di docker-compose.
 *   3. Il container gluetun (profilo `vpn`) legge OPENVPN_USER /
 *      OPENVPN_PASSWORD / SERVER_COUNTRIES e si connette al server Proton
 *      migliore (Plus → server ottimizzati per streaming).
 *   4. Il proxy HTTP locale (porta 8888) viene esposto al container
 *      paramount come http://gluetun:8888.
 *
 * NOTA: il restart effettivo del container gluetun NON può essere fatto
 * dall'addon (manca di accesso al socket Docker). Viene fatto da:
 *   - scripts/install-gluetun-watcher.sh: una systemd path unit che osserva
 *     vpn-data/gluetun.env e fa `docker compose --profile vpn restart
 *     gluetun` automaticamente ad ogni cambio.
 *   - In alternativa, scripts/restart-gluetun.sh manualmente.
 */

import { promises as fs } from 'fs';
import path from 'path';
import { VPN_DATA_PATHS } from './storage';

// Lista country code ISO-3166-1 alpha-2 riconosciuti da gluetun (vedi docs).
// Le selezioni qui sotto sono server ottimizzati per streaming US, dove
// Paramount+ funziona senza blocchi geografici.
export const PROTON_COUNTRIES = [
    { code: 'US', label: 'United States (default per Paramount+)' },
    { code: 'NL', label: 'Netherlands' },
    { code: 'CH', label: 'Switzerland' },
    { code: 'SE', label: 'Sweden' },
    { code: 'IS', label: 'Iceland' },
    { code: 'RO', label: 'Romania' },
] as const;

export type ProtonLoginConfig = {
    kind: 'proton-login';
    username: string;        // OpenVPN/IKEv2 username (NON account password)
    password: string;        // OpenVPN/IKEv2 password
    country: string;         // ISO country code (es. "US")
    updatedAt: string;
};

export type ProxyConfig = {
    kind: 'proxy';
    url: string;
    updatedAt: string;
};

export type SetupConfig = ProtonLoginConfig | ProxyConfig;

const WIREGUARD_DIR = path.dirname(VPN_DATA_PATHS.wireguardConf);

/**
 * Scrive il file env_file che docker-compose monta sul container gluetun.
 * Questo file contiene le credenziali OpenVPN in chiaro: è accettabile perché
 * - Il volume sull'host è di proprietà di root con permessi 0o600.
 * - Il container gluetun lo legge come env_file (read-only nel compose).
 * - L'utente è consapevole che le creds Proton sono salvate in chiaro sul VPS.
 *
 * Restituisce i path scritti.
 */
export async function writeProtonLoginEnv(cfg: ProtonLoginConfig): Promise<{
    envPath: string;
}> {
    await fs.mkdir(VPN_DATA_DIR, { recursive: true, mode: 0o700 });
    // Cancella eventuali file WireGuard legacy.
    await fs.rm(WIREGUARD_DIR, { recursive: true, force: true });
    const lines = [
        '# Auto-generated by /api/vpn/setup — DO NOT EDIT BY HAND.',
        '# Per rimuovere: clicca "Reset" nella card VPN in /configure.',
        `OPENVPN_USER=${shellQuote(cfg.username)}`,
        `OPENVPN_PASSWORD=${shellQuote(cfg.password)}`,
        `SERVER_COUNTRIES=${shellQuote(cfg.country)}`,
        '',
    ];
    await fs.writeFile(VPN_DATA_PATHS.gluetunEnv, lines.join('\n'), { mode: 0o600 });
    return { envPath: VPN_DATA_PATHS.gluetunEnv };
}

const VPN_DATA_DIR = path.dirname(VPN_DATA_PATHS.gluetunEnv);

/**
 * Restituisce lo stato corrente leggendo il file env (se presente).
 * Non decifra nulla: legge solo il file env sul disco (per /api/vpn/status).
 */
export async function readCurrentConfig(): Promise<{
    kind: 'proton-login' | 'proxy' | 'none';
    login?: { usernameMasked: string; country: string; envPath: string; updatedAt: string };
    proxy?: { url: string };
}> {
    try {
        const raw = await fs.readFile(VPN_DATA_PATHS.gluetunEnv, 'utf8');
        const env = parseEnvFile(raw);
        if (env.OPENVPN_USER && env.OPENVPN_PASSWORD) {
            const u = env.OPENVPN_USER;
            const masked = u.length > 4 ? u.slice(0, 2) + '…' + u.slice(-2) : '***';
            return {
                kind: 'proton-login',
                login: {
                    usernameMasked: masked,
                    country: env.SERVER_COUNTRIES || 'US',
                    envPath: VPN_DATA_PATHS.gluetunEnv,
                    updatedAt: await (async () => {
                        try {
                            const s = await fs.stat(VPN_DATA_PATHS.gluetunEnv);
                            return s.mtime.toISOString();
                        } catch {
                            return new Date().toISOString();
                        }
                    })(),
                },
            };
        }
        return { kind: 'none' };
    } catch (err: any) {
        if (err?.code === 'ENOENT') return { kind: 'none' };
        throw err;
    }
}

/** Rimuove il config VPN e la cartella wireguard legacy. */
export async function clearConfig(): Promise<void> {
    await Promise.all([
        fs.unlink(VPN_DATA_PATHS.gluetunEnv).catch(e => e?.code !== 'ENOENT' && Promise.reject(e)),
        fs.rm(WIREGUARD_DIR, { recursive: true, force: true }),
    ]);
}

// ─── helpers ────────────────────────────────────────────────────────────────

function shellQuote(v: string): string {
    // Quote con singoli apici per valori che possono contenere caratteri speciali.
    // Le credenziali OpenVPN di Proton possono contenere `+` e altri char.
    if (!v) return "''";
    return "'" + v.replace(/'/g, `'\\''`) + "'";
}

function parseEnvFile(content: string): Record<string, string> {
    const out: Record<string, string> = {};
    for (const line of content.split('\n')) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) continue;
        const idx = trimmed.indexOf('=');
        if (idx < 0) continue;
        const key = trimmed.slice(0, idx).trim();
        let value = trimmed.slice(idx + 1).trim();
        // Rimuovi singoli apici di shellQuote.
        if (value.startsWith("'") && value.endsWith("'") && value.length >= 2) {
            value = value.slice(1, -1).replace(/'\\''/g, "'");
        }
        out[key] = value;
    }
    return out;
}
