/**
 * Manager per il container gluetun (ProtonVPN WireGuard tunnel).
 *
 * - Scrive il file .conf generato nella cartella VPN_DATA_PATHS.wireguardConf
 *   (volume condiviso col container gluetun tramite bind mount).
 * - Scrive un file `gluetun.env` con `WIREGUARD_PRIVATE_KEY` estratto dal
 *   .conf, in modo che il docker-compose possa usarlo come env_file.
 * - Restituisce l'URL del proxy HTTP locale di gluetun (default http://gluetun:8888)
 *   da inserire in PROXY_URLS.
 *
 * NOTA: il restart effettivo del container gluetun NON può essere fatto
 * dall'addon (manca di accesso al socket Docker). Viene fatto da uno
 * script di hook (`scripts/restart-gluetun.sh`) sul host che:
 *   1. osserva la modifica di vpn-data/wireguard/proton.conf
 *   2. esegue `docker compose --profile vpn restart gluetun`
 * Vedi `scripts/restart-gluetun.sh` (creato in deploy step).
 */

import { promises as fs } from 'fs';
import path from 'path';
import { VPN_DATA_PATHS } from './storage';
import { buildWireguardConf, ProtonServer, parseWireguardConf, findProtonServer, listProtonServers } from './wireguard';

export type VpnConfig = {
    kind: 'wireguard'; // modalità: tunnella tutto tramite ProtonVPN
    server: ProtonServer;
    privateKey: string;
    address: string;
    rawConf: string; // il .conf completo
};

export type ProxyConfig = {
    kind: 'proxy'; // modalità: solo proxy HTTP esterno (no VPN)
    url: string; // es. "http://user:pass@host:port"
};

export type SetupConfig = VpnConfig | ProxyConfig;

const WIREGUARD_DIR = path.dirname(VPN_DATA_PATHS.wireguardConf);

/** Scrive il config WireGuard e restituisce i path. */
export async function writeWireguardConfig(conf: VpnConfig): Promise<{ confPath: string; envPath: string }> {
    await fs.mkdir(WIREGUARD_DIR, { recursive: true, mode: 0o700 });
    await fs.writeFile(VPN_DATA_PATHS.wireguardConf, conf.rawConf, { mode: 0o600 });
    // Genera file env che docker-compose può usare come env_file (opzionale).
    const env = [
        '# Auto-generated by /api/vpn/setup — DO NOT EDIT BY HAND',
        '# Rimosso automaticamente al prossimo setup.',
        `WIREGUARD_PRIVATE_KEY=${conf.privateKey}`,
        `VPN_SERVER_COUNTRIES=${conf.server.country === 'US' ? 'United States' : conf.server.country}`,
        `WIREGUARD_ADDRESSES=${conf.address}`,
        '',
    ].join('\n');
    await fs.writeFile(VPN_DATA_PATHS.gluetunEnv, env, { mode: 0o600 });
    return { confPath: VPN_DATA_PATHS.wireguardConf, envPath: VPN_DATA_PATHS.gluetunEnv };
}

/** Legge il config corrente (se presente). */
export async function readCurrentConfig(): Promise<{
    kind: 'wireguard' | 'proxy' | 'none';
    wireguard?: { path: string; server?: ProtonServer; privateKeyMasked: string; raw: string };
    proxy?: { url: string };
}> {
    try {
        const raw = await fs.readFile(VPN_DATA_PATHS.wireguardConf, 'utf8');
        const parsed = parseWireguardConf(raw);
        if (!parsed) return { kind: 'none' };
        // Cerca il server noto con stessa publicKey.
        const server = listProtonServers().find(s => s.publicKey === parsed.publicKey);
        const maskedKey = parsed.privateKey.length > 8
            ? parsed.privateKey.slice(0, 4) + '…' + parsed.privateKey.slice(-4)
            : '***';
        return {
            kind: 'wireguard',
            wireguard: {
                path: VPN_DATA_PATHS.wireguardConf,
                server,
                privateKeyMasked: maskedKey,
                raw,
            },
        };
    } catch (err: any) {
        if (err?.code === 'ENOENT') return { kind: 'none' };
        throw err;
    }
}

/** Rimuove il config (usato quando si vuole disabilitare VPN). */
export async function clearConfig(): Promise<void> {
    await Promise.all([
        fs.unlink(VPN_DATA_PATHS.wireguardConf).catch(e => e?.code !== 'ENOENT' && Promise.reject(e)),
        fs.unlink(VPN_DATA_PATHS.gluetunEnv).catch(e => e?.code !== 'ENOENT' && Promise.reject(e)),
    ]);
}

/**
 * Costruisce un VpnConfig a partire da un input grezzo dell'utente.
 *  - confText: testo .conf completo incollato dall'utente
 *  - serverCode: se fornito (es. "US-NJ#153"), viene usato al posto di quello nel .conf
 */
export function buildVpnConfigFromText(
    confText: string,
    serverCode?: string,
): VpnConfig {
    const parsed = parseWireguardConf(confText);
    if (!parsed) {
        throw new Error('Config WireGuard non valido (mancano Interface.PrivateKey o Peer.PublicKey)');
    }
    let server: ProtonServer | undefined;
    if (serverCode) {
        // serverCode fornito dall'utente → usa quello (override).
        // Cerca nei server noti (per nome) oppure costruisci un "custom" usando
        // endpoint/publicKey dal .conf parsato.
        server = findProtonServer(serverCode);
        if (!server) {
            server = {
                country: 'US',
                city: 'Custom',
                code: serverCode,
                endpoint: parsed.endpoint,
                publicKey: parsed.publicKey,
                port: parsed.port,
            };
        }
    } else {
        // Prova a trovare un server noto per la publicKey del .conf.
        const known = listProtonServers().find(s => s.publicKey === parsed.publicKey);
        if (!known) {
            server = {
                country: 'US',
                city: 'Custom (from .conf)',
                code: `CUSTOM-${parsed.endpoint}`,
                endpoint: parsed.endpoint,
                publicKey: parsed.publicKey,
                port: parsed.port,
            };
        } else {
            server = known;
        }
    }
    // Costruisci il .conf finale (con la privateKey + server scelto).
    const rawConf = buildWireguardConf(parsed.privateKey, server, parsed.address);
    return {
        kind: 'wireguard',
        server,
        privateKey: parsed.privateKey,
        address: parsed.address,
        rawConf,
    };
}

/** Costruisce un VpnConfig da una private key + serverCode. */
export function buildVpnConfigFromKey(
    privateKey: string,
    serverCode: string,
): VpnConfig {
    const server = findProtonServer(serverCode);
    if (!server) {
        throw new Error(`Server ProtonVPN sconosciuto: ${serverCode}. Usa /api/vpn/servers per la lista.`);
    }
    const rawConf = buildWireguardConf(privateKey, server);
    return {
        kind: 'wireguard',
        server,
        privateKey,
        address: '10.2.0.2/32',
        rawConf,
    };
}
